### ISSUE TITLE
validateRecursively with collections always return an error!

### ISSUE THREAD

**Issue by nomadinteractif** [FiguredLimited/vue-mc#92]
Hello ! 

Let's say I have a Profile Model and MetaCollection attribute

**Model:**

```
defaults(){
        return {
            profile_id : null,
            // other profile atts
            metas:new MetaCollection(),
        }
}
```
When I validate the Model, it always return an error even if the Model doesn't have any validation define.

This would be cause by the Model function validateAttribute... see comment for a quick fix.

 ```
    /**
     * Validates a specific attribute of this model, and sets errors for it.
     *
     * @returns {boolean} `true` if valid, `false` otherwise.
     */
    validateAttribute(attribute) {
        if (!this.has(attribute)) {
            return Promise.reject(new Error(`'${attribute}' is not defined`));
        }

        let value   = this.get(attribute);
        let rules   = this.getValidateRules(attribute);
        let tasks   = rules.map((rule) => rule(value, attribute, this));

        // Check if any nested values should be validated also.
        if (this.getOption('validateRecursively')) {
            if (isFunction(get(value, 'validate'))) {
//
//comment#1 : value.validate() return an array structured like this [[{ ErrorModel1 },{ ErrorModel2 },...]] 
//
                tasks.push(value.validate());
            }
        }

        return Promise.all(tasks).then((errors) => {

            // Errors will always be messages or nested error objects.
//
//comment#2 
// when we filter the recursive errors structure, it always return true since e = [{ErrorModel1},{ErrorModel2},...]
//            errors = filter(errors, (e) => isString(e) || isObject(e));
//then we should filter in case of the recursive structure
            errors = filter(errors, (e) => {
                if(isArray(e)){
                    e = filter(e,(e2) => isString(e2) || (isObject(e2)&&!isEmpty(e2)));
                }
                return isString(e) || (isObject(e)&&!isEmpty(e));
            });   
//end quick fix

            // Set errors for the model being validated.
            this.setAttributeErrors(attribute, errors);

            // Check to see if we should yield only the first error.
            if (this.getOption('useFirstErrorOnly') && !isEmpty(errors)) {
                return first(errors);
            }

            return errors;
        });
    }
```
I have not much test this, but seems to work !

Thank you

**Comment by rtheunissen** [comment]
So right now when you have a collection in a model, and that collection has a few models in it that are valid (so the collection is valid), the outer model will have a non-empty errors response upon validation, eg. `{ c: [ [ {}, {} ] ] }`. 

Would it make sense to remove that `c` and its empty errors if _all_ of them are empty? Otherwise it is impossible to tell which model in the collection failed validation. I also think that maybe it should be `{ c: [ {}, {} ] }` in the first place, right?

**Comment by rtheunissen** [comment]
This has been fixed and released as part of [v0.6.0](https://github.com/FiguredLimited/vue-mc/releases/tag/v0.6.0).

**Comment by nmsmith22389** [comment]
I'm still seeing this same problem when an attribute is a model. *(haven't check with collections yet)*
